### ISSUE TITLE
Could you release the train/val/test split used in the paper?

### ISSUE THREAD

**Issue by notabigfish** [kotori-y/mpek#2]
Hi,

thanks for the great job! The process of creating train/val/test splits are well described in the paper. I found the kcat and km test sets in the supplymentary materials, but cannot find the exact train and validation sets. As MPEK might be cited as a benchmark, could you also release the exact split you used?  Thanks!

**Comment by kotori-y** [comment]
Hello,

We have uploaded the training, validation, and test datasets used in this work to this [release](https://github.com/kotori-y/mpek/releases/tag/v1.0.0).
